typography_spectrum: 0.8042546128854156
color:
  brandStrength: 0.6406424872111529
  lightness: 0.9651241677347571
  saturation: 0.26114315539598465
  rhythmicContrast: 0.6001798291690648
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
layout_spectrum: 0.37579923192970455
author:
  name: Rodolfo Schilling
  email: rodolfo.schilling@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e750eae-01ff-4e29-9da6-33225fa847ad.jpg
name: Rodolfo Schilling
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/383abc80-844f-47d6-b386-b4ff8ce40355.jpg
title: 'Somos seres Energía, libres y armónicos.'
description: No vivimos en la realidad sino en resultados de nuestras  propias creaciones.
